auctions/urls.py
from django.urls import path

from . import views

app_name = "auctions"

urlpatterns = [
    path("", views.index, name="index"),
    path("login", views.login_view, name="login"),
    path("logout", views.logout_view, name="logout"),
    path("register", views.register, name="register"),
    path("create", views.create, name="create"),
    path("watchlist", views.watchlist, name="watchlist"),
    path("remove/watchlist", views.remove_watchlist, name='remove_watchlist' ),
    path("product/bid", views.product_bid, name = "product_bid"),
    path("product/close", views.product_close, name = "product_close"),
    path("product/comment", views.product_comment, name = "product_comment"),
    path("product/<str:name>", views.product, name="product") 
]

commerce/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings  # new
from django.conf.urls.static import static  # new

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("auctions.urls"))
]

if settings.DEBUG:  
        urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)  

auctions/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class User(AbstractUser):
    pass

    def __str__(self):
        return self.username


class Listing(models.Model):
    choice_category = [
        ("AN", "Anime"),
        ("CR", "Cars"),
        ("NA", "Nature"),
        ("SP", "Self Portrait")
    ]

    title = models.CharField(max_length = 64)
    description = models.CharField(max_length=1000)
    category = models.CharField(choices = choice_category, max_length = 50)
    bid = models.IntegerField()
    user = models.CharField(max_length = 64)
    active = models.BooleanField(default = False)
    bidder = models.CharField(max_length = 64, blank = True)
    image = models.ImageField(upload_to="images/", blank=True)


    def __str__(self):
        return f"{self.title}"

class WatchList(models.Model):
    item = models.ForeignKey(Listing, on_delete = models.CASCADE , related_name="watchlist")
    person = models.ForeignKey(User, on_delete = models.CASCADE, related_name = "person")

    def __str__(self):
        return f"{self.item}"


class Comment(models.Model):
    item = models.ForeignKey(Listing, on_delete = models.CASCADE, related_name="comments")
    commenter = models.ForeignKey(User, on_delete = models.CASCADE, related_name = "commenter")
    comment = models.CharField(max_length = 1000)
    
    def __str__(self):
        return f"{self.commenter}'s comment on {self.item}"

auctions/forms.py
from django.forms import ModelForm
from django import forms
from .models import *

# class NewForm(forms.Form):
#     title = forms.CharField(label="Title", required=True, widget=forms.TextInput(attrs={"placeholder" : "Title", "class" : "form-control"}))
#     description =  forms.CharField(label="Description", required = True, widget=forms.Textarea(attrs={"placeholder" : "description", "class" : "form-control"} ))


# class NewForm_two(forms.Form):
#     number = forms.IntegerField(label= False, required=True, widget=forms.NumberInput(attrs={"placeholder" : "Number", "class" : "form_number form-control" }) )
#     image = forms.ImageField(label= False )


class UploadForm(ModelForm):

    class Meta():
        model = Listing
        fields = "__all__"
        labels = {
            "title" : "",
            "description" : "",
            "bid" : "",
            "image" : ""      
        }


        widgets= {
            "title" : forms.TextInput(attrs={"class" : "form-control", "placeholder" : "Title"}),
            'description' : forms.Textarea(attrs={"class" : "form-control", "placeholder" : "Description"}),
            'bid' : forms.NumberInput(attrs={"class" : "form-control form_number", "placeholder" : "Price"}),
            "category" : forms.Select(attrs={"class" : "form-control"})
        }

class BidForm(ModelForm):

    class Meta():
        model = Listing
        fields = ("bid",)

        labels = {
            "bid" : "New bid",
        }

        widgets = {
            'bid' : forms.NumberInput(attrs={"class" : "form-control"})
        }


class CommentForm(ModelForm):

    class Meta():
        model = Comment
        fields = ("comment",)
        labels = {
            "comment" : "Comment"
        }
        
        
        widgets = {
            'comment' : forms.Textarea(attrs={"class" : "form-control form_text", "placeholder" : "Make a comment"})
        }

auctions/views.py
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.db import IntegrityError
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse
from .forms import *

from .models import *


def index(request):
    listing = Listing.objects.filter(active = False)
    return render(request, "auctions/index.html", {
        "listing" : listing
    })


def login_view(request):
    if request.method == "POST":

        # Attempt to sign user in
        username = request.POST["username"]
        password = request.POST["password"]
        user = authenticate(request, username=username, password=password)

        # Check if authentication successful
        if user is not None:
            login(request, user)
            return HttpResponseRedirect(reverse("auctions:index"))
        else:
            return render(request, "auctions/login.html", {
                "message": "Invalid username and/or password."
            })
    else:
        return render(request, "auctions/login.html")


def logout_view(request):
    logout(request)
    return HttpResponseRedirect(reverse("auctions:index"))


def register(request):
    if request.method == "POST":
        username = request.POST["username"]
        email = request.POST["email"]
        # Ensure password matches confirmation
        password = request.POST["password"]
        confirmation = request.POST["confirmation"]
        if password != confirmation:
            return render(request, "auctions/register.html", {
                "message": "Passwords must match."
            })

        # Attempt to create new user
        try:
            user = User.objects.create_user(username, email, password)
            user.save()
        except IntegrityError:
            return render(request, "auctions/register.html", {
                "message": "Username already taken."
            })
        login(request, user)
        return HttpResponseRedirect(reverse("auctions:index"))
    else:
        return render(request, "auctions/register.html")


@login_required
def create(request):
    # Once a request comes in with a post method
    if request.method == "POST":
        form = UploadForm(request.POST, request.FILES)

        # you validate the form
        if form.is_valid():
            form.save()
            return create_error(request, "Successfully filled data")

        else:
            return create_error(request, "Unsucessful")          

    else:
        return render(request, "auctions/create.html", {
            "form" : UploadForm(),
        })
   
    
@login_required   
def watchlist(request):
    # once it is accessed view the post method alongside certain details
    # you get the particular Listing object and save that object as a new Watchlist
    # you are also redirected to your index page 
    if request.method == "POST":
        id = request.POST["list_data"]
        user_data = request.POST["user_data"]
        wl = Listing.objects.get(pk = id)
        user_obj = User.objects.get(pk = user_data)
        new = WatchList(item = wl, person = user_obj)
        new.save()
        return HttpResponseRedirect(reverse("auctions:index"))
    
    # if it is accessed through get you create an empty list and you also try to query the entire model
    # You then loop through each object of the Wachlist filtering each Listing to find out which has a
    # title like the current index, and then you append the first index of the queryset and you display the list 
    else:
        new_watchlist = []
        wl = WatchList.objects.filter(person = request.user.pk)
        for i in wl:
            new_w = Listing.objects.filter(title = i)
            new_watchlist.append(new_w[0])

        return render(request, "auctions/watchlist.html", {
            "watchlist" : new_watchlist
        })

@login_required   
def remove_watchlist(request):
    if request.method == "POST":
        new_id = request.POST['list_data']
        list = Listing.objects.get(pk = new_id)
        wl = WatchList.objects.get(item = list).delete()
        return HttpResponseRedirect(reverse("auctions:watchlist"))



def product(request, name):
    list = Listing.objects.get(title = name)
    comm = Comment.objects.filter(item = list.pk)
    form = BidForm()
    comment = CommentForm()
    return render(request, "auctions/product.html", {
        "list" : list,
        "form" : form,
        "comment" : comment,
        "comments" : comm
    })

@login_required
def product_bid(request):
    if request.method == "POST":
        bid = request.POST['bid']
        list_id = request.POST['list_data']
        list_user = request.POST['list_user']
        list = Listing.objects.get(pk = list_id)
        if list.bid >= int(bid):
            return HttpResponseRedirect(reverse("auctions:product", args = [list.title]))
        else:
            list.bid = bid
            list.bidder = list_user
            list.save()
            return render(request, "auctions/product.html", {
                "message" : "Successfully placed a Bid"
            })
        

@login_required
def product_close(request):
    if request.method == "POST":
        list_id = request.POST['list_data']
        list = Listing.objects.get(pk = list_id)
        list.active = True
        list.save()
        return render(request, "auctions/product.html", {
            "message" : "Successfully Closed the Bid"
        })
    
@login_required
def product_comment(request):
    if request.method == "POST":
        list_id = request.POST['list_data']
        list_user = request.POST['list_user']
        comment = request.POST['comment']
        list = Listing.objects.get(pk = list_id)
        user = User.objects.get(pk = list_user)
        comm = Comment(item = list, commenter = user, comment = comment)
        comm.save()
        return HttpResponseRedirect(reverse("auctions:product" , args=[list.title]))

    
def create_error(request, str):
    return render(request, "auctions/create.html", {
        "form" : UploadForm(),
        "message" : str
    })

auctions/templates/auctions/create.html
{% extends 'auctions/layout.html' %}

{% block title %}
  List your Item
{% endblock %}

{% block body %}
  <div class="content_main">
    <h2>What item do you wish to List</h2>
    <form action=" {% url 'auctions:create' %} " method="post" enctype="multipart/form-data">
      {% csrf_token %}
      {{ form.title }}
      {{ form.description }}

      <div class="form_two">
        {{ form.bid }}
        {{ form.image }}
      </div>

      {{form.category}}
      
        <input type="hidden" name="user" value="{{request.user}}">
      

      <div class="submit">
        <input class="submit-btn btn btn-primary" type="submit" value="Submit" />
      </div>
      
      {% if message %}
        {{ message }}
      {% endif %}
    </form>
  </div>
{% endblock %}

auctions/templates/auctions/index.html
{% extends 'auctions/layout.html' %}

{% block body %}
  <h2>Active Listings</h2>

  {{ content|safe }}

  {% for list in listing %}
    <div class="card my-3" style="width: 20rem; ">
      <a href="{% url "auctions:product" list.title %}">
        <img src="{{ list.image.url }}" class="card-img-top" alt="..." />
      </a>
      <div class="card-body">
        <h5 class="card-title">{{ list.title }}</h5>
        <p class="card-text">{{ list.description }}.</p>
        <p class="card-text">Listed By: {{ list.user }}</p>
        <p class="card-text">Price: ${{ list.bid }}</p>
        <div class="card_form">
          <form action="{% url 'auctions:watchlist' %}" method="post">
            {% csrf_token %}
            <input type="hidden" name="list_data" value="{{ list.pk }}" />
            <input type="hidden" name="user_data" value="{{ request.user.pk }}" />
            <button class="btn btn-secondary my-1 w-100">Add to Wishlist</button>
          </form>
          <a href=" {% url "auctions:product" list.title %} ">
            <button class="btn btn-success my-1 w-100">Bid</button>
          </a>
        </div>
      </div>
    </div>
  {% endfor %}
{% endblock %}

auctions/templates/auctions/layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <title>{% block title %}Auctions{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="{% static 'auctions/styles.css' %}" rel="stylesheet">
        <link href="{% static 'auctions/create.css' %}" rel="stylesheet">
    </head>
    <body>
        <h1>Auctions</h1>
        <div>
            {% if user.is_authenticated %}
                Signed in as <strong>{{ user.username }}</strong>.
            {% else %}
                Not signed in.
            {% endif %}
        </div>
        <ul class="nav">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'auctions:index' %}">Active Listings</a>
            </li>
            {% if user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" href="">Categories</a>
                </li>

                <li class="nav-item">
                    <a class="nav-link" href="{% url "auctions:watchlist" %}">Watchlist</a>
                </li>

                <li class="nav-item">
                    <a class="nav-link" href="{% url 'auctions:create' %}">Create Listing</a>
                </li>

                <li class="nav-item">
                    <a class="nav-link" href="{% url 'auctions:logout' %}">Log Out</a>
                </li>
            {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'auctions:login' %}">Log In</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'auctions:register' %}">Register</a>
                </li>
            {% endif %}
        </ul>
        <hr>
        {% block body %}
        {% endblock %}
    </body>
</html>

auctions/templates/auctions/login.html
{% extends "auctions/layout.html" %}

{% block body %}

    <h2>Login</h2>

    {% if message %}
        <div>{{ message }}</div>
    {% endif %}

    <form action="{% url 'auctions:login' %}" method="post">
        {% csrf_token %}
        <div class="form-group">
            <input autofocus class="form-control" type="text" name="username" placeholder="Username">
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name="password" placeholder="Password">
        </div>
        <input class="btn btn-primary" type="submit" value="Login">
    </form>

    Don't have an account? <a href="{% url 'auctions:register' %}">Register here.</a>

{% endblock %}

auctions/templates/auctions/product.html
{% extends 'auctions/layout.html' %}

{% block body %}
  {% if message %}
    <div class="message">{{ message }}</div>
  {% else %}
    <div class="product_card">
      <div class="card mb-3 w-100">
        <img src="{{ list.image.url }}" class="card-img-top" alt="..." />
        <div class="card-body">
          <h5 class="card-title">{{ list.title }}</h5>
          <p class="card-text">{{ list.description }}.</p>
          <p class="card-text">
            <small class="text-body-secondary">By: {{ list.user }}</small>
          </p>
          <p class="card-text">
            <small class="text-body-secondary">Min Bid : {{ list.bid }}</small>
          </p>
          <p class="card-text">
            <small class="text-body-secondary">Last updated 3 mins ago</small>
          </p>

          <!-- If a user clicks on a product which he uploaded himself it shows a different form from one he did not upload -->
          {% if request.user.username == list.user %}
            <form action="{% url 'auctions:product_close' %}" method="post">
              {% csrf_token %}
              <input type="hidden" name="list_data" value="{{ list.pk }}" />
              <input class="btn btn-danger" type="submit" value="Close Bid" />
            </form>
          {% else %}
            <form action=" {% url 'auctions:product_bid' %} " method="post">
              {% csrf_token %}
              <input type="hidden" name="list_data" value="{{ list.pk }}" />
              <input type="hidden" name="list_user" value="{{ request.user }}" />
              {{ form.bid }}
              <input class="btn btn-success mb-3" type="submit" value="Place bid" />
            </form>
        </div>
      </div>
    </div>
            <form action="{% url 'auctions:product_comment' %}" method="post">
              {% csrf_token %}
              <input type="hidden" name="list_data" value="{{ list.pk }}" />
              <input type="hidden" name="list_user" value="{{ request.user.id }}" />
              {{ comment.comment }}
              <input class="btn btn-secondary" type="submit" value="Comment" />
            </form>
          {% endif %}
        

    {% for comm in comments %}
      <div class="card">
        <div class="card-header">{{ comm.commenter }}</div>
        <div class="card-body">
          <blockquote class="blockquote mb-0">
            <p> {{comm.comment}} </p>
            <footer class="blockquote-footer">
              <cite title="Source Title"> {{comm.commenter}} </cite>
            </footer>
          </blockquote>
        </div>
      </div>
    {% endfor %}
  {% endif %}
{% endblock %}

auctions/templates/auctions/register.html
{% extends "auctions/layout.html" %}

{% block body %}

    <h2>Register</h2>

    {% if message %}
        <div>{{ message }}</div>
    {% endif %}

    <form action="{% url 'auctions:register' %}" method="post">
        {% csrf_token %}
        <div class="form-group">
            <input class="form-control" autofocus type="text" name="username" placeholder="Username">
        </div>
        <div class="form-group">
            <input class="form-control" type="email" name="email" placeholder="Email Address">
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name="password" placeholder="Password">
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name="confirmation" placeholder="Confirm Password">
        </div>
        <input class="btn btn-primary" type="submit" value="Register">
    </form>

    Already have an account? <a href="{% url 'auctions:login' %}">Log In here.</a>

{% endblock %}

auctions/templates/auctions/watchlist.html
{% extends "auctions/layout.html" %}

{% block body %}
  <h2>Active Listings</h2>

  {{ content|safe }}

  {% if request.user.is_authenticated %}
    {% for list in watchlist %}
      <div class="card my-3" style="width: 20rem; ">
        <img src="{{ list.image.url }}" class="card-img-top" alt="..." />
        <div class="card-body">
          <h5 class="card-title">{{ list.title }}</h5>
          <p class="card-text">{{ list.description }}.</p>
          <p class="card-text">Price: ${{ list.bid }}</p>
          <div class="card_form">
            <form action="{% url "auctions:remove_watchlist" %}" method="post" >
              {% csrf_token %}
              <input type="hidden" name="list_data" value="{{ list.pk }}">
              <button class="btn btn-danger my-1 w-100"> Remove </button>
            </form>
            <form action="">
              {% csrf_token %}
              <input type="hidden" name="list_data" value="{{ list.pk }}">
              <button href="#" class="btn btn-success my-1 w-100">Bid</button>
            </form>
          </div>
          
        </div>
      </div>
    {% endfor %}
  {% endif %} 


{% endblock %}